export const SET_USER = "SET_USER";
export const SET_USER_FAIL = "SET_USER_FAIL";
export const LOG_OUT = "LOG_OUT";

export const GET_JOURNALS_START = "GET_JOURNALS_START";
export const GET_JOURNALS_SUCCESS = "GET_JOURNALS_SUCCESS";
export const GET_JOURNALS_FAIL = "GET_JOURNALS_FAIL";

export const WRITE_JOURNAL_START = "WRITE_JOURNAL_START";
export const WRITE_JOURNAL_SUCCESS = "WRITE_JOURNAL_SUCCESS";
export const WRITE_JOURNAL_FAIL = "WRITE_JOURNAL_FAIL";

export const EDIT_JOURNAL_START = "EDIT_JOURNAL_START";
export const EDIT_JOURNAL_SUCCESS = "EDIT_JOURNAL_SUCCESS";
export const EDIT_JOURNAL_FAIL = "EDIT_JOURNAL_FAIL";

export const DELETE_JOURNAL_START = "DELETE_JOURNAL_START";
export const DELETE_JOURNAL_SUCCESS = "DELETE_JOURNAL_SUCCESS";
export const DELETE_JOURNAL_FAIL = "DELETE_JOURNAL_FAIL";

export const EMPTY_JOURNALS_ON_LOGOUT = "EMPTY_JOURNALS_ON_LOGOUT";
